language: scala
script:
  - sbt +test
  - sbt -Dakka.build.version=2.6.0-M7 clean test
scala:
  - 2.13.1
jdk:
  - openjdk8
  - openjdk11
before_script:
  - mkdir $TRAVIS_BUILD_DIR/tmp
  - export SBT_OPTS="-Djava.io.tmpdir=$TRAVIS_BUILD_DIR/tmp"
sudo: false
